server:
  port: 8080

logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.apache.kafka.*: ERROR

spring:
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: mandates